# 형태소 분석

In [2]:
import sys
from pathlib import Path

# 프로젝트 루트: notebooks/ 하위 어느 깊이에서 실행해도 동작
_cwd = Path.cwd().resolve()
for _d in [_cwd, *_cwd.parents]:
    if (_d / "code" / "notebook_bootstrap.py").is_file():
        sys.path.insert(0, str(_d / "code"))
        break
else:
    raise FileNotFoundError("code/notebook_bootstrap.py 을 찾을 수 없습니다. cwd=" + str(_cwd))

from notebook_bootstrap import setup_paths

PROJECT_ROOT = setup_paths()
from project_paths import DATA_CAFE_ONLY, DATA_INTEGRATED, CONFIG_STOPWORDS

# 파일 불러오기
import pandas as pd
import re

df = pd.read_csv(DATA_CAFE_ONLY / '의대증원_cafedata_preprocess.csv') 

print(f"네이버 카페 데이터 개수: {len(df)}")

df.head(10)

네이버 카페 데이터 개수: 3712

,title,doc,like,comment_cnt,comment_list,ch,date,section
0,2026학년도 의과대학 수시모집 교과 일반전형 3,인제대는 작년 내신성적을 반영할 때 국영수 과학 상위 2과목만 반영하는 산식으로 다...,16,6,[{'comment_content': '잘 읽어보았습니다 한눈에 전체 내용이 잘 들...,cafe,2025-06-29,4
1,추가 의대증원 이야기 나오던데,최근에 뉴스 보니까 의대 또 추가증원한다는것 같던데 이거 사실인가요 어디서 본거 같...,0,1,[{'comment_content': '올해는 일단 유예됐는데 취소가 아니라 유예된...,cafe,2025-06-30,4
2,sky 질문,언미생사 all 백분위 96인 1이고 영어는 고정 1인데 서연고 중에 어디가 제일 ...,0,3,[{'comment_content': '뭐가 기준인지는 모르겠지만 수능은 생각보다 ...,cafe,2025-06-29,4
3,수시 6장 머리터지기 시작했어요,글쓰기 전 선검색 바랍니다 미취학글 과외구인글 아이디 추천글 댓글 달린 글 삭제시 ...,1,11,[{'comment_content': '전체내신나오고 아이의 생기부가 어느정도 파악...,cafe,2025-06-30,4
4,고3 수시 대학 라인 문제,고1 고3 필수 학종 합격 가이드 1 학생 학부모 여부 본인및 자녀의 학년 예 고3...,1,2,"[{'comment_content': '같은 고민 입니다 어렵네요', 'commen...",cafe,2025-06-30,4
5,약대도 증원소식이 있나요,약대도 증원된다만다 이야기가 있고 2026년 대비 전략 이런 글들이 많던데약대 내년...,0,1,[{'comment_content': '증원얘기는 따로 없는것 같던데 예전에 약대 ...,cafe,2025-06-30,4
6,수박먹고 대학간다 기본편 2026,이번 중위권 간담뢰 다녀와서 본격적으로 공부하려 책을 펼칩니다 아이 등급에 따라 여...,10,15,"[{'comment_content': '보고 계신 건 기본편인거죠 제목 미스매치',...",cafe,2025-06-30,4
7,재수생 학부모 계신가요 궁금한게 있는데,1 게시글과 덧글은 성의있고 예의바르게 작성하도록 합니다 게시글은 PC로 최소 7줄...,1,10,[{'comment_content': '에고 전직 삼수생으로써 6평 잘봤다고 풀어지...,cafe,2025-06-30,4
8,보건복지부장관 정은경 지명됐네요,정회원 등업대기 공간입니다 카페 취지에 맞지 않는 글은 임의 삭제 될 수 있습니다 ...,6,45,"[{'comment_content': '인사청문회에서 물어뜯기면 어떡하죠', 'co...",cafe,2025-06-29,4
9,목차,1 시계편 전쟁은 계산이다 2024년 2월 6일 의대증원 정책이 발표되었고 20일 ...,4,4,[{'comment_content': '오 손자병법이었나요 어려운 내용을 겪어낸 일...,cafe,2025-06-27,4

In [62]:
from kiwipiepy import Kiwi
from tqdm import tqdm


# 1. 인스턴스(일꾼) 생성 - 반드시 소문자 변수에 담아서 사용
kiwi = Kiwi()

title_token_list = [] # 형태소 분석 전체 결과를 담을 리스트
title_token_noun = [] # 2글자 이상 명사만 담을 리스트

for i in tqdm(range(len(df))) :
    # 데이터가 비어있을 경우를 대비해 문자열로 변환
    text = str(df['title'][i])

    # 형태소 분석 ( Kiwi는 tokenize를 사룔)
    tokens = kiwi.tokenize(text)

    # 전체 결과 저장
    pos_result = [(t.form, t.tag) for t in tokens]
    title_token_list.append(pos_result)

    # 명사 추출
    nouns = [t.form for t in tokens if t.tag in ['NNG', 'NNP'] and len(t.tag) > 1]
    title_token_noun.append(nouns)

Quantization is not supported for ArchType::neon. Fall back to non-quantized model.
Quantization is not supported for ArchType::neon. Fall back to non-quantized model.
100%|█████████████████████████████████████| 3712/3712 [00:02<00:00, 1740.22it/s]

In [5]:
print(title_token_list)

[[('2026', 'SN'), ('학년도', 'NNG'), ('의과', 'NNG'), ('대학', 'NNG'), ('수시', 'NNG'), ('모집', 'NNG'), ('교과', 'NNG'), ('일반', 'NNG'), ('전형', 'NNG'), ('3', 'SN')], [('추가', 'NNG'), ('의대', 'NNG'), ('증원', 'NNG'), ('이야기', 'NNG'), ('나오', 'VV'), ('던데', 'EF')], [('sky', 'SL'), ('질문', 'NNG')], [('수시', 'NNG'), ('6', 'SN'), ('장', 'NNG'), ('머리', 'NNG'), ('터지', 'VV'), ('기', 'ETN'), ('시작', 'NNG'), ('하', 'XSV'), ('었', 'EP'), ('어요', 'EF')], [('고', 'NNG'), ('3', 'SN'), ('수시', 'NNG'), ('대학', 'NNG'), ('라인', 'NNG'), ('문제', 'NNG')], [('약대', 'NNG'), ('도', 'JX'), ('증원', 'NNG'), ('소식', 'NNG'), ('이', 'JKS'), ('있', 'VA'), ('나요', 'EF')], [('수박', 'NNG'), ('먹', 'VV'), ('고', 'EC'), ('대학', 'NNG'), ('가', 'VV'), ('ᆫ다', 'EF'), ('기본', 'NNG'), ('편', 'NNB'), ('2026', 'SN')], [('재수', 'NNG'), ('생', 'XSN'), ('학부모', 'NNG'), ('계시', 'VV'), ('ᆫ가요', 'EF'), ('궁금하', 'VA'), ('ᆫ', 'ETM'), ('것', 'NNB'), ('이', 'JKS'), ('있', 'VV'), ('는데', 'EC')], [('보건', 'NNG'), ('복지', 'NNG'), ('부', 'NNG'), ('장관', 'NNG'), ('정은경', 'NNP'), ('지명', 'NNG'), ('되', 'XSV'), ('었', 'EP'), ('네요', 'EF')], [('목차', 'NNG')], [('굿', 'NNG'), ('모닝', 'NNP'), ('6', 'SN'), ('월', 'NNB'), ('27', 'SN'), ('일', 'NNB'), ('금', 'MAJ'), ('오늘', 'NNG'), ('의', 'JKG'), ('뉴스', 'NNG')], [('25', 'SN'), ('년', 'NNB'), ('6', 'SN'), ('월', 'NNB'), ('27', 'SN'), ('일', 'NNB'), ('금요일', 'NNG'), ('간추리', 'VV'), ('ᆫ', 'ETM'), ('숏', 'NNG'), ('뉴스', 'NNG')], [('이재명', 'NNP'), ('의대', 'NNG'), ('증원', 'NNG'), ('윤곽', 'NNG'), ('지자체', 'NNG'), ('벌써', 'MAG'), ('공공', 'NNG'), ('의대', 'NNG'), ('유치', 'NNG'), ('전', 'NNG')], [('대학', 'NNG'), ('합격', 'NNG'), ('만', 'JX'), ('하', 'VV'), ('면', 'EC'), ('끝', 'NNG'), ('이', 'VCP'), ('ᆯ', 'ETM'), ('줄', 'NNB'), ('알', 'VV'), ('었', 'EP'), ('는데', 'EC')], [('합격자', 'NNG'), ('분포', 'NNG'), ('표', 'NNG'), ('어디', 'NP'), ('서', 'JKB'), ('보', 'VV'), ('ᆯ', 'ETM'), ('수', 'NNB'), ('있', 'VA'), ('나요', 'EF')], [('공중', 'NNG'), ('보건', 'NNG'), ('장학', 'NNG'), ('생', 'XSN'), ('경기도', 'NNP'), ('지역', 'NNG')], [('2026', 'SN'), ('학년도', 'NNG'), ('의과', 'NNG'), ('대학', 'NNG'), ('수시', 'NNG'), ('모집', 'NNG'), ('교과', 'NNG'), ('일반', 'NNG'), ('전형', 'NNG'), ('1', 'SN')], [('이재명', 'NNP'), ('표', 'NNG'), ('의대', 'NNG'), ('증원', 'NNG'), ('의', 'JKG'), ('문제점', 'NNG')], [('로미오', 'NNP'), ('샘', 'NNG'), ('의', 'JKG'), ('2026', 'SN'), ('학년도', 'NNG'), ('대입', 'NNG'), ('정시', 'NNG'), ('설명회', 'NNG'), ('핵심', 'NNG'), ('정리', 'NNG'), ('6', 'SN'), ('월', 'NNB'), ('26', 'SN'), ('일', 'NNB'), ('제미나이', 'NNP'), ('정리', 'NNG')], [('티처스', 'NNP'), ('반수', 'NNG'), ('생', 'XSN'), ('현실', 'NNG'), ('적', 'XSN'), ('으로', 'JKB'), ('어떻', 'VA-I'), ('ᆫ가요', 'EF')], [('고교', 'NNG'), ('학점', 'NNG'), ('제', 'XSN'), ('절대', 'NNG'), ('평가', 'NNG'), ('로', 'JKB'), ('수정', 'NNG'), ('되', 'XSV'), ('나', 'EC')], [('다', 'MAG'), ('주택', 'NNG'), ('규제', 'NNG'), ('가', 'JKS'), ('양극', 'NNG'), ('화', 'XSN'), ('초래', 'NNG')], [('괜찮', 'VA'), ('은', 'ETM'), ('뉴스', 'NNG'), ('2026', 'SN'), ('의대', 'NNG'), ('정원', 'NNG'), ('확정', 'NNG')], [('교육부', 'NNG'), ('학사', 'NNG'), ('유연', 'NNG'), ('화', 'XSN'), ('없', 'VA'), ('다', 'EF'), ('재', 'XPN'), ('확인', 'NNG'), ('의대', 'NNG'), ('생', 'XSN'), ('들', 'XSN'), ('요구', 'NNG'), ('일축', 'NNG')], [('고', 'NNG'), ('1', 'SN'), ('성적', 'NNG')], [('지방', 'NNG'), ('일반고', 'NNG'), ('내신', 'NNG'), ('1', 'SN'), ('8', 'SN'), ('수시', 'NNG')], [('안녕', 'NNG'), ('하', 'XSA'), ('세요', 'EF'), ('전직', 'NNG'), ('간호사', 'NNG'), ('이', 'VCP'), ('ᆸ니다', 'EF'), ('간호사', 'NNG'), ('절대', 'MAG'), ('하', 'VV'), ('시', 'EP'), ('면', 'EC'), ('안', 'MAG'), ('되', 'VV'), ('ᆸ니다', 'EF')], [('6', 'SN'), ('월', 'NNB'), ('17', 'SN'), ('일', 'NNB'), ('부산', 'NNP'), ('진로', 'NNG'), ('진학', 'NNG'), ('센터', 'NNG'), ('중앙대', 'NNP'), ('ppt', 'SL'), ('자료', 'NNG')], [('서울아산병원', 'NNP'), ('은', 'JX'), ('대', 'NNB'), ('국민', 'NNG'), ('앞', 'NNG'), ('에서', 'JKB'), ('사과', 'NNG'), ('하', 'XSV'), ('라', 'EF')], [('2026', 'SN'), ('학년도', 'NNG'), ('수시', 'NNG'), ('전형', 'NNG'), ('서울과기대', 'NNG'), ('한국기술교육대', 'NNG'), ('한국공학대', 'NNG')], [('일반고', 'NNG'), ('내신', 'NNG'), ('4', 'SN'), ('점', 'NNB'), ('대', 'XSN'), ('이', 'VCP'), ('면', 'EC'), ('수시로', 'MAG'), ('어느', 'MM'), ('정도', 'NNG'), ('의', 'JKG'), ('학교', 'NNG'), ('가', 'VV'), ('나요', 'EF')], [('대학', 'NNG'), ('어디', 'NP'), ('가', 'JKS'), ('입', 'NNG'), ('결', 'NNG'), ('은', 'JX'), ('작년도', 'NNG'), ('것', 'NNB'), ('만', 'JX'), ('조회', 'NNG'), ('되', 'VV'), ('나요', 'EF')], [('그래서', 'MAJ'), ('의대', 'NNG'), ('증원', 'NNG'), ('왜', 'MAG'), ('반대', 'NNG'), ('하', 'XSV'), ('었', 'EP'), ('던', 'ETM'), ('거', 'NNB'), ('이', 'VCP'), ('ᆷ', 'EF')], [('수시', 'NNG'), ('전략', 'NNG'), ('설명회', 'NNG'), ('후기', 'NNG')], [('페북', 'NNP')], [('연고', 'NNG'), ('대', 'NNG'), ('25', 'SN'), ('입', 'NNG'), ('결', 'NNG')], [('뉴스', 'NNG'), ('모음', 'NNG'), ('안철수', 'NNP'), ('대통령', 'NNG'), ('AI', 'SL'), ('100', 'SN'), ('조', 'NNB'), ('구상', 'NNG'), ('의대', 'NNG'), ('2000', 'SN'), ('명', 'NNB'), ('증원', 'NNG'), ('과', 'JC'), ('놀라', 'VV'), ('ᆯ', 'ETM'), ('만치', 'NNB'), ('닮', 'VV'), ('어', 'EF')], [('의대', 'NNG'), ('수시', 'NNG'), ('준비', 'NNG'), ('중', 'NNB'), ('이', 'VCP'), ('라면', 'EC'), ('꼭', 'MAG'), ('보', 'VV'), ('어야', 'EC'), ('하', 'VX'), ('ᆯ', 'ETM'), ('설명회', 'NNG'), ('소도스카이', 'NNG')], [('후기', 'NNG'), ('전국', 'NNG'), ('의대', 'NNG'), ('수시', 'NNG'), ('전략', 'NNG'), ('설명회', 'NNG')], [('충남', 'NNP'), ('수', 'NNG'), ('1', 'SN'), ('44', 'SN')], [('nan', 'SL')], [('시대인재', 'NNP'), ('렉스', 'NNP'), ('고', 'NNG'), ('3', 'SN'), ('이과', 'NNG'), ('입시', 'NNG'), ('설명회', 'NNG'), ('5', 'SN')], [('수의대', 'NNG'), ('궁금하', 'VA'), ('어서', 'EC'), ('요', 'JX')], [('올해', 'NNG'), ('가', 'JKS'), ('22', 'SN'), ('23', 'SN'), ('보다', 'JKB'), ('정시', 'NNG'), ('로', 'JKB'), ('서성', 'XR'), ('한', 'MM'), ('가', 'VV'), ('기', 'ETN')], [('의대', 'NNG'), ('반수', 'NNG')], [('3', 'SN'), ('년', 'NNB'), ('전', 'NNG'), ('으로', 'JKB'), ('돌아가', 'VV'), ('고', 'EC'), ('싶', 'VX'), ('어요', 'EF'), ('보수', 'NNG'), ('가', 'JKS'), ('부활', 'NNG'), ('하', 'XSV'), ('나', 'EC'), ('하', 'VV'), ('었', 'EP'), ('더니만', 'EC')], [('대학', 'NNG'), ('병원', 'NNG'), ('만', 'JX'), ('어떻게', 'MAG'), ('좀', 'MAG')], [('진짜', 'MAG'), ('입시', 'NNG'), ('너무', 'MAG'), ('어렵', 'VA-I'), ('은데', 'EC'), ('도와주', 'VV'), ('세요', 'EF')], [('올해', 'NNG'), ('메디컬', 'NNG'), ('은', 'JX'), ('역대', 'NNG'), ('최고', 'NNG'), ('로', 'JKB'), ('어렵', 'VA-I'), ('지', 'EC'), ('않', 'VX'), ('을까요', 'EF')], [('중앙대', 'NNP'), ('중앙대', 'NNP'), ('2025', 'SN'), ('입', 'NNG'), ('결', 'NNG'), ('및', 'MAG'), ('2026', 'SN'), ('수시', 'NNG'), ('주요', 'NNG'), ('변경', 'NNG'), ('사항', 'NNG')], [('의대', 'NNG'), ('정원', 'NNG'), ('최소', 'NNG'), ('5000', 'SN'), ('명', 'NNB'), ('선', 'NNG'), ('유지', 'NNG'), ('공공', 'NNG'), ('의대', 'NNG'), ('권역', 'NNG'), ('별', 'XSN'), ('신설', 'NNG'), ('건의', 'NNG')], [('작년', 'NNG'), ('대학', 'NNG'), ('입시', 'NNG'), ('설명회', 'NNG'), ('참석', 'NNG'), ('후기', 'NNG')], [('공유', 'NNG'), ('약대', 'NNG'), ('수시', 'NNG'), ('와', 'JC'), ('정시', 'NNG'), ('입시', 'NNG'), ('결과', 'NNG'), ('를', 'JKO'), ('통합', 'NNG'), ('하', 'XSV'), ('어서', 'EC'), ('보', 'VV'), ('면', 'EC')], [('인제대', 'NNP'), ('의대', 'NNG'), ('수시', 'NNG'), ('교과', 'NNG'), ('전형', 'NNG'), ('어떻', 'VA-I'), ('게', 'EC'), ('되', 'VV'), ('ᆯ까요', 'EF')], [('중앙대', 'NNP'), ('수시', 'NNG'), ('요강', 'NNG'), ('확정', 'NNG'), ('2026', 'SN'), ('VS', 'SL'), ('2025', 'SN'), ('무엇', 'NP'), ('이', 'JKS'), ('바뀌', 'VV'), ('었', 'EP'), ('나', 'EC'), ('공유', 'NNG')], [('아침', 'NNG'), ('단상', 'NNG'), ('2', 'SN')], [('대치동', 'NNP'), ('출신', 'NNG'), ('들', 'XSN'), ('이', 'JKS'), ('N', 'SL'), ('수', 'NNG'), ('에', 'JKB'), ('실패', 'NNG'), ('하', 'XSV'), ('는', 'ETM'), ('흔하', 'VA'), ('ᆫ', 'ETM'), ('이유', 'NNG')], [('통근', 'NNG'), ('거리', 'NNG'), ('의', 'JKG'), ('초', 'XPN'), ('저', 'XPN'), ('출산', 'NNG'), ('에', 'JKB'), ('대하', 'VV'), ('ᆫ', 'ETM'), ('영향', 'NNG'), ('과', 'JC'), ('정책', 'NNG'), ('적', 'XSN'), ('함의', 'NNG')], [('단독', 'NNG'), ('대통령', 'NNG'), ('첫', 'MM'), ('국무', 'NNG'), ('회의', 'NNG'), ('서', 'JKB'), ('복지', 'NNG'), ('장관', 'NNG'), ('님', 'XSN'), ('자살', 'NNG'), ('률', 'XSN'), ('왜', 'MAG'), ('이리', 'MAG'), ('높', 'VA'), ('나요', 'EF')], [('올해', 'NNG'), ('수능', 'NNG'), ('국어', 'NNG'), ('핵불', 'NNG'), ('이', 'VCP'), ('ᆯ', 'ETM'), ('거', 'NNB'), ('같', 'VA'), ('음', 'EF')], [('이재명', 'NNP'), ('을', 'JKO'), ('향하', 'VV'), ('ᆫ', 'ETM'), ('운석', 'NNG'), ('열', 'NNG'), ('의', 'JKG'), ('짝사랑', 'NNG')], [('2025', 'SN'), ('년도', 'NNB'), ('대입', 'NNG'), ('정시', 'NNG'), ('입', 'NNG'), ('결', 'NNG'), ('AI', 'SL'), ('분석', 'NNG'), ('의대', 'NNG'), ('증원', 'NNG'), ('200', 'SN'), ('명', 'NNB'), ('이', 'JKS'), ('초래', 'NNG'), ('하', 'XSV'), ('ᆫ', 'ETM'), ('기존', 'NNG'), ('질서', 'NNG'), ('붕괴', 'NNG')], [('재수', 'NNG'), ('를', 'JKO'), ('진지', 'XR'), ('하', 'XSA'), ('게', 'EC'), ('고민', 'NNG'), ('하', 'XSV'), ('어야', 'EC'), ('하', 'VX'), ('는', 'ETM'), ('이유', 'NNG')], [('6', 'SN'), ('월', 'NNB'), ('6', 'SN'), ('일', 'NNB'), ('분당', 'NNP'), ('청', 'NNG'), ('솔', 'NNG'), ('6', 'SN'), ('모', 'NNG'), ('분석', 'NNG'), ('설명회', 'NNG'), ('by', 'SL'), ('김병진', 'NNP'), ('소장', 'NNG')], [('올해', 'NNG'), ('스카이', 'NNP'), ('입', 'NNG'), ('결', 'NNG'), ('상승', 'NNG'), ('무', 'XPN'), ('조건', 'NNG'), ('이', 'VCP'), ('ᆫ', 'ETM'), ('거', 'NNB'), ('같', 'VA'), ('네요', 'EF')], [('대차', 'VA'), ('ᆫ', 'ETM'), ('설명회', 'NNG'), ('김경태', 'NNP'), ('소장', 'NNG'), ('님', 'XSN'), ('의리', 'NNG'), ('버전', 'NNG'), ('4', 'SN')], [('의대', 'NNG'), ('26', 'SN'), ('학번', 'NNG'), ('usmle', 'SL'), ('응시', 'NNG'), ('가능', 'NNG'), ('하', 'XSA'), ('ᆯ까요', 'EF')], [('대차', 'VA'), ('ᆫ', 'ETM'), ('설명회', 'NNG'), ('김경태', 'NNP'), ('소장', 'NNG'), ('님', 'XSN'), ('의리', 'NNG'), ('버전', 'NNG'), ('1', 'SN')], [('백분위', 'NNG'), ('94', 'SN'), ('96', 'SN'), ('1', 'SN'), ('99', 'SN'), ('97', 'SN'), ('이', 'VCP'), ('면', 'EC'), ('문', 'NNG'), ('과', 'JC'), ('한의대', 'NNG'), ('되', 'VV'), ('나요', 'EF')], [('영재', 'NNG'), ('고', 'NNG'), ('의대', 'NNG'), ('반수', 'NNG')], [('텔', 'NNG'), ('그', 'MM'), ('입', 'NNG'), ('결', 'NNG'), ('작년', 'NNG'), ('기준', 'NNG'), ('이', 'VCP'), ('ᆷ', 'EF')], [('스쿨', 'NNG'), ('기사', 'NNG'), ('보', 'VV'), ('니', 'EC'), ('너무', 'MAG'), ('화나', 'VV'), ('네요', 'EF')], [('문재인', 'NNP'), ('이', 'JKS'), ('당선', 'NNG'), ('되', 'XSV'), ('었', 'EP'), ('을', 'ETM'), ('때', 'NNG'), ('좌파', 'NNG'), ('친구', 'NNG'), ('한테', 'JKB'), ('하', 'VV'), ('ᆫ', 'ETM'), ('말', 'NNG'), ('이', 'JKS'), ('떠오르', 'VV'), ('네요', 'EF')], [('문수', 'NNP'), ('패거리', 'NNG'), ('공격', 'NNG'), ('목표', 'NNG'), ('는', 'JX'), ('점', 'NNG'), ('광', 'NNG'), ('후', 'NNG'), ('이', 'VCP'), ('니', 'EC'), ('각종', 'NNG'), ('이단', 'NNG'), ('귀신', 'NNG'), ('세력', 'NNG'), ('들', 'XSN'), ('에', 'JKB'), ('집중', 'NNG'), ('하', 'XSV'), ('면', 'EC'), ('좋', 'VA'), ('을', 'ETM'), ('거', 'NNB'), ('같', 'VA'), ('습니다', 'EF')], [('예상', 'NNG'), ('보다', 'JKB'), ('과탐', 'NNG'), ('1', 'SN'), ('표본', 'NNG'), ('이', 'JKS'), ('높', 'VA'), ('지', 'EC'), ('않', 'VX'), ('어', 'EC'), ('보이', 'VV'), ('ᆸ니다', 'EF')], [('의대', 'NNG'), ('교수', 'NNG'), ('들', 'XSN'), ('복지부', 'NNG'), ('교육부', 'NNG'), ('국방부', 'NNG'), ('장관', 'NNG'), ('의정', 'NNG'), ('갈등', 'NNG'), ('해소', 'NNG'), ('에', 'JKB'), ('적극', 'NNG'), ('나서', 'VV'), ('어야', 'EC')], [('확', 'MAG'), ('통', 'NNG'), ('사탐', 'NNG'), ('을', 'JKO'), ('하', 'VV'), ('어도', 'EC'), ('상위', 'NNG'), ('권', 'XSN'), ('공대', 'NNG'), ('가능', 'NNG'), ('하', 'XSA'), ('ᆫ가요', 'EF')], [('중', 'NNG'), ('3', 'SN'), ('국어', 'NNG'), ('토론', 'NNG')], [('중앙대학교', 'NNP'), ('입학', 'NNG'), ('설명회', 'NNG'), ('후기', 'NNG')], [('이미', 'MAG'), ('이', 'MM'), ('사건', 'NNG'), ('때', 'NNG'), ('다음', 'NNG'), ('정권', 'NNG'), ('교체', 'NNG'), ('는', 'JX'), ('정하', 'VV'), ('어', 'EC'), ('지', 'VX'), ('어', 'EC'), ('있', 'VX'), ('었', 'EP'), ('어요', 'EF')], [('국정', 'NNG'), ('운영', 'NNG'), ('에', 'JKB'), ('대하', 'VV'), ('어서', 'EC'), ('는', 'JX'), ('기대', 'NNG'), ('안', 'MAG'), ('하', 'VV'), ('지만', 'EC'), ('의사', 'NNG'), ('들', 'XSN'), ('핍박', 'NNG'), ('하', 'XSV'), ('고', 'EC'), ('환자', 'NNG'), ('와', 'JC'), ('의사', 'NNG'), ('의', 'JKG'), ('관계', 'NNG'), ('를', 'JKO'), ('멀', 'VV'), ('게', 'EC'), ('하', 'VX'), ('ᆫ', 'ETM'), ('윤석열', 'NNP'), ('정부', 'NNG'), ('인사', 'NNG'), ('들', 'XSN'), ('에', 'JKB'), ('대하', 'VV'), ('어서', 'EC'), ('는', 'JX'), ('철저히', 'MAG'), ('조사', 'NNG'), ('하', 'XSV'), ('기', 'ETN'), ('ᆯ', 'JKO')], [('6', 'SN'), ('모', 'NNG'), ('국어', 'NNG'), ('평가', 'NNG')], [('수의학', 'NNG'), ('에', 'JKB'), ('대하', 'VV'), ('ᆫ', 'ETM'), ('이해', 'NNG'), ('진로', 'NNG'), ('및', 'MAG'), ('전망', 'NNG'), ('입시', 'NNG'), ('준비', 'NNG'), ('도움', 'NNG'), ('자료', 'NNG')], [('윤', 'NNP'), ('통', 'NNG'), ('은', 'JX'), ('왜', 'MAG'), ('계엄', 'NNG'), ('하', 'XSV'), ('었', 'EP'), ('을까요', 'EF')], [('진짜', 'NNG'), ('배기', 'XSN'), ('친중', 'NNG'), ('좌파', 'NNG'), ('정치인', 'NNG'), ('은', 'JX'), ('이', 'MM'), ('녀석', 'NNB'), ('이', 'VCP'), ('지', 'EF')], [('서울', 'NNP'), ('공대', 'NNG'), ('매년', 'MAG'), ('130', 'SN'), ('명', 'NNB'), ('이탈', 'NNG'), ('이대로', 'MAG'), ('는', 'JX'), ('AI', 'SL'), ('미래', 'NNG'), ('없', 'VA'), ('다', 'EF')], [('07', 'SN'), ('년', 'NNB'), ('생', 'XSN'), ('아이', 'NNG'), ('들', 'XSN'), ('이', 'JKS'), ('많', 'VA'), ('어서', 'EC')], [('윤', 'NNG'), ('이', 'JKS'), ('보수', 'NNG'), ('망치', 'VV'), ('었', 'EP'), ('죠', 'EF'), ('어찌', 'MAG'), ('탄핵', 'NNG'), ('때', 'NNG'), ('와', 'JKB'), ('패턴', 'NNG'), ('이', 'JKS'), ('똑같', 'VA'), ('나요', 'EF')], [('공유', 'NNG'), ('2026', 'SN'), ('단국대', 'NNP'), ('의대', 'NNG'), ('40', 'SN'), ('명', 'NNB'), ('선발', 'NNG'), ('수시', 'NNG'), ('논술', 'NNG'), ('4', 'SN'), ('교과', 'NNG'), ('지역', 'NNG'), ('10', 'SN'), ('학', 'NNG'), ('종', 'NNG'), ('12', 'SN')], [('건강', 'NNG'), ('보험료', 'NNG'), ('체납', 'NNG'), ('되', 'XSV'), ('었', 'EP'), ('어요', 'EF'), ('클릭', 'NNG'), ('하', 'XSV'), ('면', 'EC'), ('위험', 'NNG')], [('의대', 'NNG'), ('지역', 'NNG'), ('인재', 'NNG'), ('전형', 'NNG'), ('선발', 'NNG'), ('비율', 'NNG'), ('은', 'JX'), ('60', 'SN'), ('이상', 'NNG'), ('으로', 'JKB'), ('예상', 'NNG'), ('되', 'XSV'), ('ᆫ다고', 'EC')], [('문자', 'NNG'), ('공유', 'NNG'), ('소', 'NNG'), ('도', 'JX'), ('수시', 'NNG'), ('전략', 'NNG'), ('설명회', 'NNG')], [('공유', 'NNG'), ('2026', 'SN'), ('6', 'SN'), ('월', 'NNB'), ('모평', 'NNG'), ('역대', 'NNG'), ('급', 'NNG'), ('최', 'XPN'), ('상위', 'NNG'), ('권', 'XSN'), ('경쟁', 'NNG')], [('고', 'NNG'), ('3', 'SN'), ('내신', 'NNG'), ('반등', 'NNG'), ('쉽', 'VA-I'), ('지', 'EC'), ('않', 'VX'), ('네요', 'EF')], [('내년', 'NNG'), ('의대', 'NNG'), ('모집', 'NNG'), ('3123', 'SN'), ('명', 'NNB'), ('지역', 'NNG'), ('인재', 'NNG'), ('전형', 'NNG'), ('늘', 'VV'), ('어', 'EC'), ('호남', 'NNP'), ('강원', 'NNP'), ('학생', 'NNG'), ('유리', 'NNG')], [('공유', 'NNG'), ('정시', 'NNG'), ('2025', 'SN'), ('학년도', 'NNG'), ('정시', 'NNG'), ('입', 'NNG'), ('결', 'NNG'), ('분석', 'NNG'), ('자연', 'NNG'), ('계열', 'NNG'), ('연고', 'NNG'), ('대', 'NNB'), ('1', 'SN'), ('오스카', 'NNP'), ('카페', 'NNG')], [('강하', 'VA'), ('ᆫ', 'ETM'), ('학원', 'NNG'), ('세', 'MM'), ('종', 'NNG'), ('2026', 'SN'), ('의대', 'NNG'), ('모집', 'NNG'), ('3', 'SN'), ('123', 'SN'), ('명', 'NNB'), ('수도', 'NNG'), ('권', 'XSN'), ('vs', 'SL'), ('비', 'XPN'), ('수도', 'NNG'), ('권', 'XSN'), ('경쟁', 'NNG'), ('률', 'XSN'), ('전망', 'NNG'), ('은', 'JX'), ('어떻', 'VA-I'), ('게', 'EC'), ('되', 'VV'), ('나', 'EC'), ('대구', 'NNP'), ('경북', 'NNP'), ('지역', 'NNG'), ('지역', 'NNG'), ('인재', 'NNG'), ('전형', 'NNG'), ('주목', 'NNG')], [('의대', 'NNG'), ('모집', 'NNG'), ('인원', 'NNG')], [('공유', 'NNG'), ('37', 'SN'), ('개', 'NNB'), ('약대', 'NNG'), ('2025', 'SN'), ('정시', 'NNG'), ('입결', 'NNP'), ('베리타스', 'NNP'), ('알파', 'NNG')], [('올해', 'NNG'), ('6', 'SN'), ('모', 'MM'), ('응시', 'NNG'), ('최대', 'NNG'), ('이', 'VCP'), ('라고', 'EC'), ('하', 'VV'), ('네요', 'EF')], [('요즘', 'NNG'), ('동국대', 'NNP'), ('병원', 'NNG'), ('예약', 'NNG'), ('안', 'MAG'), ('하', 'VV'), ('고', 'EC'), ('당일', 'NNG'), ('진료', 'NNG'), ('되', 'VV'), ('ᆯ까요', 'EF')], [('레벨', 'NNG'), ('80', 'SN'), ('숙제', 'NNG')], [('서울대학교', 'NNP'), ('2026', 'SN'), ('학년도', 'NNG'), ('대입', 'NNG'), ('변화', 'NNG'), ('요약', 'NNG')], [('올해', 'NNG'), ('비', 'XPN'), ('영어', 'NNP'), ('권', 'XSN'), ('국제', 'NNG'), ('학교', 'NNG'), ('로', 'JKB'), ('전학', 'NNG'), ('오', 'VV'), ('ᆫ', 'ETM'), ('PYP', 'SL'), ('아이', 'NNG'), ('들', 'XSN'), ('3', 'SN'), ('특', 'NNG'), ('고민', 'NNG'), ('이', 'VCP'), ('ᆸ니다', 'EF')], [('초록', 'NNG'), ('이', 'JKS'), ('는', 'JX'), ('내리', 'VV'), ('어', 'EC'), ('놓', 'VX'), ('고', 'EC'), ('활동', 'NNG'), ('하', 'VV'), ('겠', 'EP'), ('습니다', 'EF')], [('부모', 'NNG'), ('가', 'JKS'), ('아이', 'NNG'), ('에게', 'JKB'), ('냉정', 'NNG'), ('하', 'XSA'), ('ᆫ', 'ETM'), ('현실', 'NNG'), ('을', 'JKO'), ('말', 'NNG'), ('하', 'XSV'), ('어', 'EC'), ('주', 'VX'), ('는', 'ETM'), ('것', 'NNB'), ('이', 'JKS'), ('맞', 'VV'), ('는', 'ETM'), ('거', 'NNB'), ('이', 'VCP'), ('ᆯ까요', 'EF')], [('지역', 'NNG'), ('인재', 'NNG'), ('선발', 'NNG'), ('늘', 'VV'), ('고', 'EC'), ('의대', 'NNG'), ('정원', 'NNG'), ('원점', 'NNG'), ('회귀', 'NNG'), ('수도', 'NNG'), ('권', 'XSN'), ('수험', 'NNG'), ('생', 'XSN'), ('의대', 'NNG'), ('입학', 'NNG'), ('문', 'NNG'), ('좁', 'VA-R'), ('어', 'EC'), ('지', 'VX'), ('나', 'EF')], [('6', 'SN'), ('모', 'NNG'), ('응시자', 'NNG'), ('가', 'JKS'), ('늘어나', 'VV'), ('ᆫ', 'ETM'), ('이유', 'NNG')], [('고', 'NNG'), ('3', 'SN'), ('황금', 'NNG'), ('돼지띠', 'NNG'), ('가', 'JKS'), ('겪', 'VV'), ('은', 'ETM'), ('입시', 'NNG'), ('롤러코스터', 'NNG')], [('전북대', 'NNP'), ('의대', 'NNG'), ('이번', 'NNG'), ('에', 'JKB'), ('수시', 'NNG'), ('정시', 'NNG'), ('지역', 'NNG'), ('인재', 'NNG'), ('각각', 'MAG'), ('몇몇', 'NR'), ('선발', 'NNG'), ('하', 'XSV'), ('는지', 'EC'), ('알', 'VV'), ('ᆯ', 'ETM'), ('수', 'NNB'), ('있', 'VA'), ('나요', 'EF')], [('불', 'XPN'), ('공평', 'NNG'), ('하', 'XSA'), ('ᆫ', 'ETM'), ('거', 'NNB'), ('ᆯ', 'JKO'), ('알', 'VV'), ('는데', 'EC'), ('어떻', 'VA-I'), ('게', 'EC'), ('하', 'VV'), ('ᆯ', 'ETM'), ('수', 'NNB'), ('없', 'VA'), ('을', 'ETM'), ('때', 'NNG')], [('전공의', 'NNG'), ('와', 'JC'), ('교수', 'NNG'), ('차이', 'NNG'), ('가', 'JKS'), ('무엇', 'NP'), ('이', 'VCP'), ('ᆫ가요', 'EF')], [('원광대학교', 'NNP'), ('2026', 'SN'), ('학년도', 'NNG'), ('수시', 'NNG'), ('모집', 'NNG'), ('요강', 'NNG'), ('발표', 'NNG'), ('되', 'XSV'), ('ᆷ', 'EF')], [('공유', 'NNG'), ('N', 'SL'), ('수생', 'NNG'), ('전성', 'NNG'), ('시대', 'NNG'), ('주범', 'NNG'), ('정', 'NNP'), ('시', 'NNG'), ('40', 'SN'), ('강제', 'NNG'), ('공정', 'NNG'), ('성', 'XSN'), ('강화', 'NNG'), ('방안', 'NNG'), ('이후', 'NNG'), ('교육', 'NNG'), ('불', 'XPN'), ('평등', 'NNG'), ('심화', 'NNG')], [('명문', 'NNG'), ('의대', 'NNG'), ('생', 'XSN'), ('응급과', 'NNG'), ('가', 'VV'), ('ᆯ', 'ETM'), ('터', 'NNB'), ('이', 'VCP'), ('니', 'EC'), ('선처', 'NNG'), ('좀', 'MAG'), ('전', 'MM'), ('여친', 'NNG'), ('들', 'XSN'), ('100', 'SN'), ('장', 'NNB'), ('촬영', 'NNG'), ('후', 'NNG'), ('호소', 'NNG')], [('공유', 'NNG'), ('다원', 'NNG'), ('6', 'SN'), ('평', 'NNB'), ('설명회', 'NNG')], [('이거', 'NP'), ('정말', 'MAG'), ('이만', 'MAG'), ('저', 'NP'), ('만', 'JX'), ('하', 'VV'), ('ᆫ', 'ETM'), ('문제', 'NNG'), ('가', 'JKC'), ('아니', 'VCN'), ('ᆸ니다', 'EF')], [('2025', 'SN'), ('문', 'NNB'), ('과', 'JC'), ('이과', 'NNG'), ('70', 'SN'), ('컷', 'NNG'), ('가중', 'NNG'), ('평균', 'NNG'), ('순위', 'NNG')], [('이재명', 'NNP'), ('경북', 'NNP'), ('의대', 'NNG'), ('설립', 'NNG'), ('상급', 'NNG'), ('병원', 'NNG'), ('유치', 'NNG'), ('검토', 'NNG'), ('의료', 'NNG'), ('사각', 'NNG'), ('해소', 'NNG'), ('청신호', 'NNG')], [('storts', 'SL'), ('문제', 'NNG'), ('가', 'JKS'), ('심각하', 'VA'), ('다는', 'ETM'), ('우리나라', 'NNG'), ('응급실', 'NNG'), ('현실', 'NNG')], [('2025', 'SN'), ('SKY', 'SL'), ('학종', 'NNG'), ('내신', 'NNG'), ('70', 'SN'), ('컷', 'NNG'), ('2', 'SN'), ('13', 'SN'), ('등급', 'NNG'), ('2', 'SN'), ('년', 'NNB'), ('연속', 'NNG'), ('상승', 'NNG'), ('자소서', 'NNG'), ('폐지', 'NNG'), ('이후', 'NNG'), ('학종', 'NNG'), ('정량', 'NNG'), ('화', 'XSN'), ('심각', 'XR')], [('공유', 'NNG'), ('39', 'SN'), ('개', 'NNB'), ('의', 'JKG'), ('대', 'NNG'), ('입', 'NNG'), ('결', 'NNG'), ('지방', 'NNG'), ('의대', 'NNG'), ('10', 'SN'), ('곳', 'NNG'), ('중', 'NNB'), ('7', 'SN'), ('곳', 'NNG'), ('입', 'NNG'), ('결', 'NNG'), ('하락', 'NNG'), ('2026', 'SN'), ('일반', 'NNG'), ('전형', 'NNG'), ('역대', 'NNG'), ('급', 'NNG'), ('경쟁', 'NNG'), ('예고', 'NNG')], [('의대', 'NNG'), ('정원', 'NNG'), ('축소', 'NNG'), ('에', 'JKB'), ('도', 'JX'), ('N', 'SL'), ('수생', 'NNG'), ('역대', 'NNG'), ('최다', 'NNG'), ('상위', 'NNG'), ('권', 'XSN'), ('합격선', 'NNG'), ('상승', 'NNG'), ('전망', 'NNG')], [('이재명', 'NNP'), ('공약집', 'NNG'), ('최종', 'NNG'), ('정리', 'NNG'), ('정치', 'NNG'), ('군사', 'NNG'), ('외교', 'NNG'), ('등', 'NNB'), ('10', 'SN'), ('개', 'NNB'), ('항목', 'NNG')], [('중앙대', 'NNP'), ('의대', 'NNG'), ('수시', 'NNG'), ('낮', 'VA'), ('은', 'ETM'), ('이유', 'NNG')], [('주술', 'NNG'), ('풍수', 'NNG'), ('를', 'JKO'), ('경계', 'NNG'), ('하', 'XSV'), ('자', 'EC'), ('어떤', 'MM'), ('정치인', 'NNG'), ('의', 'JKG'), ('부모', 'NNG'), ('묘', 'NNG'), ('와', 'JC'), ('청와대', 'NNP'), ('흉', 'NNG'), ('지', 'NNG'), ('론', 'XSN')], [('입시', 'NNG'), ('쌍', 'NNG'), ('춘', 'NNG'), ('년', 'NNB'), ('에', 'JKB'), ('결혼', 'NNG'), ('황금', 'NNG'), ('돼지', 'NNG'), ('첫째', 'NR'), ('백', 'NR'), ('호', 'NNB'), ('둘째', 'NR'), ('반', 'NNG'), ('강제', 'NNG'), ('선착순', 'NNG'), ('인생', 'NNG'), ('저', 'MM'), ('같', 'VA'), ('으시', 'EP'), ('ᆫ', 'ETM'), ('분', 'NNB'), ('많', 'VA'), ('으시', 'EP'), ('죠', 'EF')], [('이재명', 'NNP'), ('52', 'SN'), ('vs', 'SL'), ('김문수', 'NNP'), ('4

In [63]:
# 본문 명사 추출

# 1. 인스턴스(일꾼) 생성 - 반드시 소문자 변수에 담아서 사용
kiwi = Kiwi()

document_token_list = [] # 형태소 분석 전체 결과를 담을 리스트
document_token_noun = [] # 2글자 이상 명사만 담을 리스트

for i in tqdm(range(len(df))) :
    # 데이터가 비어있을 경우를 대비해 문자열로 변환
    text = str(df['doc'][i])

    # 형태소 분석 ( Kiwi는 tokenize를 사룔)
    tokens = kiwi.tokenize(text)

    # 전체 결과 저장
    pos_result = [(t.form, t.tag) for t in tokens]
    document_token_list.append(pos_result)

    # 명사 추출
    nouns = [t.form for t in tokens if t.tag in ['NNG', 'NNP'] and len(t.tag) > 1]
    document_token_noun.append(nouns)

Quantization is not supported for ArchType::neon. Fall back to non-quantized model.
Quantization is not supported for ArchType::neon. Fall back to non-quantized model.
100%|███████████████████████████████████████| 3712/3712 [00:44<00:00, 82.68it/s]

In [57]:
print(document_token_noun[:10])

[['인제대', '작년', '내신', '성적', '반영', '때', '국영수', '과학', '상위', '과목', '반영', '학교', '내신', '반영', '방식', '특이', '학교', '직접', '비교', '대학', '공지', '작년', '기준', '컷', '인제대', '식', '등급', '만점', '기준', '경우', '국영수', '과', '과목', '반영', '대학', '일반', '등급', '정도', '해당', '국영', '수사과', '과목', '반영', '대학', '일반', '등급', '정도', '해당', '내신', '반대', '말', '올해', '국영수', '과', '과목', '정상', '반영', '수치', '내신', '컷', '등급', '정도', '상황', '의대', '정원', '낙관', '인제대', '면접', '때', '통과', '이후', '면접', '당락', '때', '반면', '해', '사실', '내신', '순', '줄', '중구난방', '예전', '면접', '최근', '면접', '때', '배수', '이후', '면접', '당락', '때', '인제대', '기본', '면접', '중요', '대학', '인하대', '경우', '작년', '정원', '와중', '작년', '등급', '탐구', '평균', '소수점', '최저', '학력', '등급', '올해', '합', '탐구', '소수점', '절', '사', '정원', '정원', '최저', '상황', '컷', '작년', '컷', '수능', '애매', '교과', '성적', '학생', '합', '합', '안전빵', '위', '합', '인하대', '합', '관동대', '건양', '대', '경상대', '합', '조선대', '강원대', '정도', '최저', '충족', '전제', '내신', '안전', '합격', '곳', '정도', '인하대', '확률', '등급', '사이', '입', '결', '방어', '인하대', '작년', '정시', '과학', '가산점', '만점', '감산점', '희', '방식', '작정', '입', '결', '방어', '올인', '개인', '주관', '평가', '그동안', '인하대', '입학처', '모습', '인칭', '주인공', '시점', '입학', '전형', '설계', '간판', '학과', '의대', '다군', '펑크', '삽', '작년', '정시', '수시', '최저', '합', '탐구', '절사', '판', '눈', '인칭', '시점', '인칭', '시점', '대학', '움직임', '고려', '대응', '수준', '레벨', '업', '대학', '지원', '수험', '입장', '학생', '움직임', '신경', '인칭', '주인공', '시점', '자신', '점수', '신경', '결과', '인칭', '시점', '학생', '동향', '대학', '인칭', '시점', '자신', '대학', '입학', '전형', '설계', '결과', '마찬가지', '전북대', '경우', '작년', '컷', '등급', '가량', '대학', '언급', '말씀', '최저', '합', '합', '최저', '을지', '대', '연대', '원주', '면접', '합', '면접', '영남대', '선호도', '대학', '합격선', '선', '입시', '결과', '대학', '대동소이', '전북대', '지역', '인재', '전형', '전북대', '공개', '지역', '인재', '전북', '컷', '등급', '결론', '말씀', '지역', '인재', '전북', '경우', '의대', '컷', '등급', '호남', '대학', '지역', '인재', '전형', '상황', '전북대', '수능', '최저', '전북대', '지역', '인재', '전북', '지원', '지역', '부', '모', '전북', '거주', '지원', '가능', '특이', '사항', '지역', '인재', '지원', '최저', '합', '상황', '사탐런', '최저', '충족', '초반', '예비', '자리', '수', '앞', '번호', '합격', '내신', '원래', '논술', '수능', '의대', '성적', '납치', '상황', '논술', '교과', '장', '전북대', '지역', '교과', '학생', '뒤', '예비', '렉스', '팀장', '상담', '학생', '내신', '등급', '학생', '탈락', '지역', '경우', '점수', '분포', '등급', '장담', '등급', '중후반', '올해', '일반', '전형', '경우', '학년도', '동일', '인원', '선발', '점', '감안', '학년도', '비', '사탐런', '최저', '점', '생각', '컷', '기준', '등급', '언저리', '정도', '제주대', '경우', '작년', '의대', '최저', '곳', '합', '탐구', '평균', '탐구', '평균', '올해', '사탐', '런', '상황', '개인', '합', '탐구', '반영', '조선대', '비교', '때', '만약', '절대', '평가', '영어', '실질', '최저', '과탐', '최저', '경우', '제주대', '조선', '국영수', '경우', '전체', '조선', '정도', '재작년', '컷', '작년', '컷', '제주대', '선발', '인원', '영향', '제주대', '경우', '반영', '식', '특이', '사항', '공통', '과목', '일반', '선택', '진로', '선택', '반영', '일반', '최근', '동향', '학년', '때', '진로', '선택', '과목', '이수', '등급', '과목', '개수', '실질', '학년', '때', '이수', '과목', '반영', '비율', '학년', '반영', '비율', '로', '효과', '대학', '제주대', '경우', '학년', '때', '내신', '학생', '상대', '유리', '구조', '점', '유의', '올해', '경우', '정원', '최저', '내신', '컷', '예전', '컷', '부근', '정도', '조선대', '경우', '의대', '최저', '학력', '등급', '합', '정도', '설정', '설정', '상대', '최저', '학력', '등급', '합', '탐구', '과목', '반영', '작년도', '재작년', '컷', '등급', '공시', '수능', '최저', '측면', '학교', '차이', '상황', '작년', '경우', '조선대', '의대', '자체', '정원', '불변', '상황', '조선대', '선호도', '대학', '의대', '정원', '최저', '차이', '조선대', '합격선', '영향', '올해', '조선대', '경우', '곳', '최저', '등급', '정원', '불변', '합격선', '영향', '안쪽', '종합', '경쟁력', '내신', '등급', '안쪽', '커트라인', '충남대', '작년', '선발', '올해', '정원', '작년', '경우', '컷', '최종', '컷', '등급', '정원', '부분', '합격선', '위', '상승', '전망', '등급', '안쪽', '충남대', '종합', '전형', '곳', '지원', '충남대', '특징', '국영', '수사과', '주요', '교과', '이외', '기타', '교과', '과목', '반영', '점', '기타', '교과', '정보', '기술', '가정', '외국어', '과목', '중요', '생각', '해당', '과목', '성적', '경우', '충남대', '지원', '가능', '정도', '타격', '점', '유의', '충남대', '등급', '국영', '수사과', '주요', '교과', '기준', '등급', '동일', '선', '충남대', '식', '등급', '국영', '수사과', '등급', '동일', '선', '충남대', '식', '등급', '국영', '수사과', '등급', '동일', '선', '입시', '결과', '해석', '때', '점', '참고', '작년', '의대', '정원', '증원', '관련', '배', '증원', '말', '탈', '대학', '충북대', '작년', '교과', '전형', '선발', '작년', '선발', '올해', '정원', '운', '펑크', '기대', '문제', '충북대', '최저', '반영', '탐구', '합', '곳', '부분', '과탐', '반영', '절사', '반영', '차이', '최저', '충족', '점', '감안', '등급', '안쪽', '컷', '회귀', '가능', '마지막', '부산대', '경우', '작년', '처음', '일반', '전형', '의대', '신입', '선발', '교과', '정량', '평가', '학업', '역량', '평가', '반영', '후자', '당락', '정량', '부분', '중요', '최저', '충남대', '비교', '때', '통상', '부산대', '선호도', '충남대', '상황', '입', '결', '차이', '발생', '충남대', '컷', '부산대', '국영수', '사과', '교과', '환산', '등급', '부산대', '컷', '작년', '선발', '정량', '평가', '부분', '기피', '올해', '경우', '정원', '점', '감안', '지원', '이상', '올해', '의대', '교과', '일반', '전형', '정리', '전반', '의대', '정원', '조정', '입', '결', '예전', '입', '결', '학년도', '회귀', '가능', '사탐런', '여파', '속', '최저', '합', '과탐', '필수', '반영', '학교', '입', '결', '합격선', '정원', '합격선', '상황', '합', '곳', '특성', '과탐', '최저', '충족', '합격선', '작년도', '학년도', '차이', '선', '보합', '마무리', '가능', '염두', '정도', '전망'], ['최근', '뉴스', '의대', '추가', '증원', '사실', '검색', '추천', '강', '생물', '노용관', '이론', '기', '출', '장성천', '기출문풀', '윤관식', '제문', '풀', '태', '후', '미적분', '문', '풀', '편입', '오준', '아카데미', '리메디', '의치', '전', '입시', '컨설팅'], ['언미생사', '백분위', '인', '영어', '고정', '연고', '유리', '올해', '재수', '의대', '증원', '폐지', '감안', '정도', '불안', '현역'], ['글', '전', '선', '검색', '취학', '글', '과외', '구인', '글', '아이디', '추천', '글', '댓글', '글', '삭제', '회원', '강등', '최하', '간', '활동', '정지', '주의', '사항', '카페', '규정', '숙지', '활동', '제한', '처리', '내용', '게시', '글', '즉시', '강제', '퇴장', '조치', '얼마', '수시', '원서', '접수', '시작', '기말고사', '기간', '시험', '부분', '걱정', '예상', '기말', '성적', '변동', '생기', '부', '내용', '고민'], ['고', '고', '필수', '학종', '합격', '가이드', '학생', '학부모', '여부', '본인', '자녀', '학년', '고', '재학', '카페', '지인', '소개', '검색', '유튜브', '검색', '희망', '대학', '학과', '유니브클래스대학', '과', '성균관대', '물리학과', '고민', '재학', '증가', '의대', '증원', '원', '복', '입', '결', '변화', '예상', '수시', '대학', '라인', '설정', '문제', '신규', '가입자', '유클카페', '특별', '선물', '리스트', '전원', '무료', '입시', '프리미엄', '패키지', '종', '무료', '탐구', '활동', '분석', '자료', '종', '무료', '합격', '탐구', '주제', '생기', '부', '디자인', '자료집', '무료', '합격', '케이스', '자료집', '무료', '수시', '원서', '접수', '시크릿', '노하우', '자료집', '무료', '계열', '탐구', '활동', '주제', '무료', '계열', '권장', '도서', '추천', '아이', '수시', '카드', '유클', '수시', '설명회', '유클', '수시', '설명회', '오픈', '급변', '입시', '판', '성공', '수시', '전략', '공개'], ['약대', '증원', '이야기', '대비', '전략', '글', '약대', '내년', '증원', '추천', '강', '생물', '노용관', '이론', '기', '출', '장성천', '기출문풀', '윤관식', '제문', '풀', '태', '후', '미적분', '문', '풀', '편입', '오준', '아카데미', '리메디', '의치', '전', '입시', '컨설팅'], ['이번', '중위', '간담', '뢰', '본격', '공부', '책', '등급', '정보', '한눈', '장점', '책', '필요', '정보', '등급', '단점', '디', '입시', '감', '부분', '유투브', '카페', '정보', '이해', '도움', '아이', '엄마', '대입', '공부', '실전', '구입'], ['게시', '글', '덧', '글', '성의', '예의', '작성', '게시', '글', '최소', '줄', '이상', '작성', '개인', '취향', '존중', '취향', '감정', '게시', '글', '덧', '글', '카페', '운영', '규정', '관련', '위반', '경고', '위반', '강', '퇴', '처리', '카페', '운영', '규정', '공지', '사항', '숙지', '당부', '집', '아들', '재수생', '휴', '학년도', '물수능', '의대증원', '지원', '수능', '재수', '역할', '고', '만족', '등급', '내일', '성적표', '고민', '아이', '요즘', '친구', '대학생', '방학', '과', '집', '공부', '눈', '고민', '아이', '주말', '얼굴', '목', '햇볕', '말', '시간', '산책', '말', '재벌', '집', '아들', '살림', '재수', '남편', '군대', '세상살이', '이섭', '다정', '아들', '정민주', '남조', '부모', '생각', '아들', '실상', '세상', '이기', '아들', '르'], ['정회원', '업', '대기', '공간', '카페', '취지', '글', '임의', '삭제', '글쓰기', '규정', '닉네임', '규정', '의대', '증원', '정도', '해법'], ['시계', '전쟁', '계산', '의대', '증원', '정책', '발표', '사직', '결정', '시간', '동안', '숙의', '과정', '시작', '싸움', '계산', '준비', '싸움', '약점', '작전', '신속', '전쟁', '중요', '투쟁', '사이', '동력', '싸움', '유불리', '고려', '대상', '모공', '편', '최고', '승리', '파업', '순간', '말', '핵', '미사일', '억지', '무기', '발사', '순간', '억지력', '의사', '해', '순간', '싸움', '군', '형편', '방어', '철저', '기회', '포착', '모집', '때', '불리', '교차', '때', '준비', '전략', '형세', '불리', '병', '편', '형세', '우세', '창출', '병력', '물', '유리', '지형', '기세', '활용', '상대', '제압', '허실', '적', '허', '실', '적', '방심', '틈', '기습', '아군', '의도', '위치', '적', '혼란', '군', '쟁', '기동', '속도', '중요', '전장', '기동력', '정보', '우위', '결정', '승부', '요소', '적', '위치', '변', '상황', '변화', '전투', '규칙', '유동', '진행', '다양', '변수', '판단', '행동', '행군', '지형', '이해', '대비', '병력', '이동', '때', '지형', '분석', '적', '움직임', '경계', '강화', '지', '형편', '지형', '전략', '지형', '전략', '설명', '지형', '판단', '패배', '구지편', '다양', '전장', '상황', '전략', '지형', '상황', '산악', '평지', '적진', '병력', '운용', '방법', '설명', '화공', '불', '이용', '공격', '전략', '불', '이용', '공격', '시기', '조건', '방법', '외', '자원', '활용', '심리전', '중요', '언급', '용', '첩자', '중요', '정보', '첩자', '활용', '전쟁', '승리', '핵심', '간첩', '적', '동태', '파악', '혼란', '유도']]

In [61]:
import ast
from tqdm import tqdm

comment_token_list = [] # 형태소 전체 결과 (단어, 태그) 리스트
comment_token_noun = [] # 2글자 이상 명사만 담는 리스트

for i in tqdm(range(len(df))):
    raw_comments = df['comment_list'][i]
    
    # 해당 게시글의 모든 댓글 결과를 합칠 임시 리스트
    post_full_tokens = []
    post_nouns_only_noun = []
    post_nouns_only_verb = []
    post_nouns_only_adj = []
    
    # 1. 데이터 타입 방어 (문자열일 경우 리스트로 변환)
    if isinstance(raw_comments, str):
        try:
            comments = ast.literal_eval(raw_comments)
        except:
            comments = []
    else:
        comments = raw_comments
        
    # 2. 분석 시작
    if isinstance(comments, list):
        for c in comments:
            if isinstance(c, dict):
                # 키 이름 확인 (comment_content)
                text = str(c.get('comment_content', ''))
                
                if text.strip():
                    tokens = kiwi.tokenize(text)
                    
                    for t in tokens:
                        # (1) 전체 결과 저장 (단어, 태그) 튜플 형태
                        post_full_tokens.append((t.form, t.tag))
                        
                        # (2) 명사 필터링 (2글자 이상 NNG, NNP)
                        if t.tag in ['NNG', 'NNP'] and len(t.form) > 1:
                            post_nouns_only_noun.append(t.form)
    
    # 게시글 단위로 최종 리스트에 추가
    comment_token_list.append(post_full_tokens)
    comment_token_noun.append(post_nouns_only_noun)

100%|███████████████████████████████████████| 3712/3712 [01:21<00:00, 45.27it/s]

# 불용어 처리(stopwords-ko.txt 기반)

In [31]:
import os
current_directory = os.getcwd()
print("현재 디렉토리:", current_directory)

현재 디렉토리: /Users/hyerimchoi/DJD/datacrolling/의대증원_중간프로젝트

In [32]:
# 불용어 사전 기반 불용어 리스트 정리
f = open(CONFIG_STOPWORDS / 'stopwords-ko.txt', 'r', encoding="UTF-8")
st = f.readlines()
f.close()

stw = []
for i in range(0, len(st)):
    stw.append(st[i].rstrip('\n'))

stw

['!',
 '"',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '...',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ';',
 '<',
 '=',
 '>',
 '?',
 '@',
 '\\',
 '^',
 '_',
 '`',
 '|',
 '~',
 '·',
 '—',
 '——',
 '‘',
 '’',
 '“',
 '”',
 '…',
 '、',
 '。',
 '〈',
 '〉',
 '《',
 '》',
 '가',
 '가까스로',
 '가령',
 '각',
 '각각',
 '각자',
 '각종',
 '갖고말하자면',
 '같다',
 '같이',
 '개의치않고',
 '거니와',
 '거바',
 '거의',
 '것',
 '것과 같이',
 '것들',
 '게다가',
 '게우다',
 '겨우',
 '견지에서',
 '결과에 이르다',
 '결국',
 '결론을 낼 수 있다',
 '겸사겸사',
 '고려하면',
 '고로',
 '곧',
 '공동으로',
 '과',
 '과연',
 '관계가 있다',
 '관계없이',
 '관련이 있다',
 '관하여',
 '관한',
 '관해서는',
 '구',
 '구체적으로',
 '구토하다',
 '그',
 '그들',
 '그때',
 '그래',
 '그래도',
 '그래서',
 '그러나',
 '그러니',
 '그러니까',
 '그러면',
 '그러므로',
 '그러한즉',
 '그런 까닭에',
 '그런데',
 '그런즉',
 '그럼',
 '그럼에도 불구하고',
 '그렇게 함으로써',
 '그렇지',
 '그렇지 않다면',
 '그렇지 않으면',
 '그렇지만',
 '그렇지않으면',
 '그리고',
 '그리하여',
 '그만이다',
 '그에 따르는',
 '그위에',
 '그저',
 '그중에서',
 '그치지 않다',
 '근거로',
 '근거하여',
 '기대여',
 '기점으로',
 '기준으로',
 '기타',
 '까닭으로',
 '까악',
 '까지',
 '까지 미치다',
 '까지도',
 '꽈당',
 '끙끙',
 '끼익',
 '나',
 '나머지는',
 '남들',
 '남짓',
 '너',
 '너희',
 '너희들',
 '네',
 '넷',
 '년',
 '논하지 않다',
 '놀라다',
 '누가 알겠는가',
 '누구',
 '다른',
 '다른 방면으로',
 '다만',
 '다섯',
 '다소',
 '다수',
 '다시 말하자면',
 '다시말하면',
 '다음',
 '다음에',
 '다음으로',
 '단지',
 '답다',
 '당신',
 '당장',
 '대로 하다',
 '대하면',
 '대하여',
 '대해 말하자면',
 '대해서',
 '댕그',
 '더구나',
 '더군다나',
 '더라도',
 '더불어',
 '더욱더',
 '더욱이는',
 '도달하다',
 '도착하다',
 '동시에',
 '동안',
 '된바에야',
 '된이상',
 '두번째로',
 '둘',
 '둥둥',
 '뒤따라',
 '뒤이어',
 '든간에',
 '들',
 '등',
 '등등',
 '딩동',
 '따라',
 '따라서',
 '따위',
 '따지지 않다',
 '딱',
 '때',
 '때가 되어',
 '때문에',
 '또',
 '또한',
 '뚝뚝',
 '라 해도',
 '령',
 '로',
 '로 인하여',
 '로부터',
 '로써',
 '륙',
 '를',
 '마음대로',
 '마저',
 '마저도',
 '마치',
 '막론하고',
 '만 못하다',
 '만약',
 '만약에',
 '만은 아니다',
 '만이 아니다',
 '만일',
 '만큼',
 '말하자면',
 '말할것도 없고',
 '매',
 '매번',
 '메쓰겁다',
 '몇',
 '모',
 '모두',
 '무렵',
 '무릎쓰고',
 '무슨',
 '무엇',
 '무엇때문에',
 '물론',
 '및',
 '바꾸어말하면',
 '바꾸어말하자면',
 '바꾸어서 말하면',
 '바꾸어서 한다면',
 '바꿔 말하면',
 '바로',
 '바와같이',
 '밖에 안된다',
 '반대로',
 '반대로 말하자면',
 '반드시',
 '버금',
 '보는데서',
 '보다더',
 '보드득',
 '본대로',
 '봐',
 '봐라',
 '부류의 사람들',
 '부터',
 '불구하고',
 '불문하고',
 '붕붕',
 '비걱거리다',
 '비교적',
 '비길수 없다',
 '비로소',
 '비록',
 '비슷하다',
 '비추어 보아',
 '비하면',
 '뿐만 아니라',
 '뿐만아니라',
 '뿐이다',
 '삐걱',
 '삐걱거리다',
 '사',
 '삼',
 '상대적으로 말하자면',
 '생각한대로',
 '설령',
 '설마',
 '설사',
 '셋',
 '소생',
 '소인',
 '솨',
 '쉿',
 '습니까',
 '습니다',
 '시각',
 '시간',
 '시작하여',
 '시초에',
 '시키다',
 '실로',
 '심지어',
 '아',
 '아니',
 '아니나다를가',
 '아니라면',
 '아니면',
 '아니었다면',
 '아래윗',
 '아무거나',
 '아무도',
 '아야',
 '아울러',
 '아이',
 '아이고',
 '아이구',
 '아이야',
 '아이쿠',
 '아하',
 '아홉',
 '안 그러면',
 '않기 위하여',
 '않기 위해서',
 '알 수 있다',
 '알았어',
 '앗',
 '앞에서',
 '앞의것',
 '야',
 '약간',
 '양자',
 '어',
 '어기여차',
 '어느',
 '어느 년도',
 '어느것',
 '어느곳',
 '어느때',
 '어느쪽',
 '어느해',
 '어디',
 '어때',
 '어떠한',
 '어떤',
 '어떤것',
 '어떤것들',
 '어떻게',
 '어떻해',
 '어이',
 '어째서',
 '어쨋든',
 '어쩔수 없다',
 '어찌',
 '어찌됏든',
 '어찌됏어',
 '어찌하든지',
 '어찌하여',
 '언제',
 '언젠가',
 '얼마',
 '얼마 안 되는 것',
 '얼마간',
 '얼마나',
 '얼마든지',
 '얼마만큼',
 '얼마큼',
 '엉엉',
 '에',
 '에 가서',
 '에 달려 있다',
 '에 대해',
 '에 있다',
 '에 한하다',
 '에게',
 '에서',
 '여',
 '여기',
 '여덟',
 '여러분',
 '여보시오',
 '여부',
 '여섯',
 '여전히',
 '여차',
 '연관되다',
 '연이서',
 '영',
 '영차',
 '옆사람',
 '예',
 '예를 들면',
 '예를 들자면',
 '예컨대',
 '예하면',
 '오',
 '오로지',
 '오르다',
 '오자마자',
 '오직',
 '오호',
 '오히려',
 '와',
 '와 같은 사람들',
 '와르르',
 '와아',
 '왜',
 '왜냐하면',
 '외에도',
 '요만큼',
 '요만한 것',
 '요만한걸',
 '요컨대',
 '우르르',
 '우리',
 '우리들',
 '우선',
 '우에 종합한것과같이',
 '운운',
 '월',
 '위에서 서술한바와같이',
 '위하여',
 '위해서',
 '윙윙',
 '육',
 '으로',
 '으로 인하여',
 '으로서',
 '으로써',
 '을',
 '응',
 '응당',
 '의',
 '의거하여',
 '의지하여',
 '의해',
 '의해되다',
 '의해서',
 '이',
 '이 되다',
 '이 때문에',
 '이 밖에',
 '이 외에',
 '이 정도의',
 '이것',
 '이곳',
 '이때',
 '이라면',
 '이래',
 '이러이러하다',
 '이러한',
 '이런',
 '이럴정도로',
 '이렇게 많은 것',
 '이렇게되면',
 '이렇게말하자면',
 '이렇구나',
 '이로 인하여',
 '이르기까지',
 '이리하여',
 '이만큼',
 '이번',
 '이봐',
 '이상',
 '이어서',
 '이었다',
 '이와 같다',
 '이와 같은',
 '이와 반대로',
 '이와같다면',
 '이외에도',
 '이용하여',
 '이유만으로',
 '이젠',
 '이지만',
 '이쪽',
 '이천구',
 '이천육',
 '이천칠',
 '이천팔',
 '인 듯하다',
 '인젠',
 '일',
 '일것이다',
 '일곱',
 '일단',
 '일때',
 '일반적으로',
 '일지라도',
 '임에 틀림없다',
 '입각하여',
 '입장에서',
 '잇따라',
 '있다',
 '자',
 '자기',
 '자기집',
 '자마자',
 '자신',
 '잠깐',
 '잠시',
 '저',
 '저것',
 '저것만큼',
 '저기',
 '저쪽',
 '저희',
 '전부',
 '전자',
 '전후',
 '점에서 보아',
 '정도에 이르다',
 '제',
 '제각기',
 '제외하고',
 '조금',
 '조차',
 '조차도',
 '졸졸',
 '좀',
 '좋아',
 '좍좍',
 '주룩주룩',
 '주저하지 않고',
 '줄은 몰랏다',
 '줄은모른다',
 '중에서',
 '중의하나',
 '즈음하여',
 '즉',
 '즉시',
 '지든지',
 '지만',
 '지말고',
 '진짜로',
 '쪽으로',
 '차라리',
 '참',
 '참나',
 '첫번째로',
 '쳇',
 '총적으로',
 '총적으로 말하면',
 '총적으로 보면',
 '칠',
 '콸콸',
 '쾅쾅',
 '쿵',
 '타다',
 '타인',
 '탕탕',
 '토하다',
 '통하여',
 '툭',
 '퉤',
 '틈타',
 '팍',
 '팔',
 '퍽',
 '펄렁',
 '하',
 '하게될것이다',
 '하게하다',
 '하겠는가',
 '하고 있다',
 '하고있었다',
 '하곤하였다',
 '하구나',
 '하기 때문에',
 '하기 위하여',
 '하기는한데',
 '하기만 하면',
 '하기보다는',
 '하기에',
 '하나',
 '하느니',
 '하는 김에',
 '하는 편이 낫다',
 '하는것도',
 '하는것만 못하다',
 '하는것이 낫다',
 '하는바',
 '하더라도',
 '하도다',
 '하도록시키다',
 '하도록하다',
 '하든지',
 '하려고하다',
 '하마터면',
 '하면 할수록',
 '하면된다',
 '하면서',
 '하물며',
 '하여금',
 '하여야',
 '하자마자',
 '하지 않는다면',
 '하지 않도록',
 '하지마',
 '하지마라',
 '하지만',
 '하하',
 '한 까닭에',
 '한 이유는',
 '한 후',
 '한다면',
 '한다면 몰라도',
 '한데',
 '한마디',
 '한적이있다',
 '한켠으로는',
 '한항목',
 '할 따름이다',
 '할 생각이다',
 '할 줄 안다',
 '할 지경이다',
 '할 힘이 있다',
 '할때',
 '할만하다',
 '할망정',
 '할뿐',
 '할수있다',
 '할수있어',
 '할줄알다',
 '할지라도',
 '할지언정',
 '함께',
 '해도된다',
 '해도좋다',
 '해봐요',
 '해서는 안된다',
 '해야한다',
 '해요',
 '했어요',
 '향하다',
 '향하여',
 '향해서',
 '허',
 '허걱',
 '허허',
 '헉',
 '헉헉',
 '헐떡헐떡',
 '형식으로 쓰여',
 '혹시',
 '혹은',
 '혼자',
 '훨씬',
 '휘익',
 '휴',
 '흐흐',
 '흥',
 '힘입어',
 '︿',
 '！',
 '＃',
 '＄',
 '％',
 '＆',
 '（',
 '）',
 '＊',
 '＋',
 '，',
 '０',
 '１',
 '２',
 '３',
 '４',
 '５',
 '６',
 '７',
 '８',
 '９',
 '：',
 '；',
 '＜',
 '＞',
 '？',
 '＠',
 '［',
 '］',
 '｛',
 '｜',
 '｝',
 '～',
 '￥']

In [33]:
# 각 문서의 제목과 본문 또는 댓글등에서 불용어 제거

for word in stw:
    for i in range(0, len(title_token_noun)) :
        # 리스트에 불용어가 있을 경우 제거
        while word in title_token_noun[i] :
            title_token_noun[i].remove(word)
    for j in range(0, len(document_token_noun)) : 
        while word in document_token_noun[j] :
            document_token_noun[j].remove(word)
    for l in range(0, len(comment_token_noun)) : 
        while word in comment_token_noun[l] :
            comment_token_noun[l].remove(word)

In [34]:
# 문서파일 docs로 적용하여 각각의 불용어 제거
df['title_token_list_pos'] = title_token_list # 형태소와 품사 리스트
df['title_token_noun'] = title_token_noun # 명사 리스트

df['document_token_list_pos'] = document_token_list
df['document_token_noun'] = document_token_noun

df['comment_token_list_pos'] = comment_token_list
df['comment_token_noun'] = comment_token_noun

In [37]:
# 불용어 처리 후 최종 파일 저장 및 불러오기
import pickle

f = open(DATA_CAFE_ONLY / "의대증원_cafedata_total_estate_press.pkl", 'wb')
pickle.dump(df, f)
f.close()

In [43]:
f = open(DATA_CAFE_ONLY / "의대증원_cafedata_total_estate_press.pkl", 'rb')
data = pickle.load(f)
f.close()
data = data.drop(columns=['comment_nouns'])
data

,title,doc,like,comment_cnt,comment_list,ch,date,section,title_token_list_pos,title_token_noun,document_token_list_pos,document_token_noun,comment_token_noun,comment_token_list_pos
0,2026학년도 의과대학 수시모집 교과 일반전형 3,인제대는 작년 내신성적을 반영할 때 국영수 과학 상위 2과목만 반영하는 산식으로 다...,16,6,[{'comment_content': '잘 읽어보았습니다 한눈에 전체 내용이 잘 들...,cafe,2025-06-29,4,"[(2026, SN), (학년도, NNG), (의과, NNG), (대학, NNG),...","[학년도, 의과, 대학, 수시, 모집, 교과, 일반, 전형]","[(인제대, NNP), (는, JX), (작년, NNG), (내신, NNG), (성...","[인제대, 작년, 내신, 성적, 반영, 국영수, 과학, 상위, 과목, 반영, 학교,...","[한눈, 전체, 내용, 부연, 설명, 감사, 객관, 인칭, 시점, 보믄, 파라미터,...","[(잘, MAG), (읽, VV), (어, EC), (보, VX), (었, EP),..."
1,추가 의대증원 이야기 나오던데,최근에 뉴스 보니까 의대 또 추가증원한다는것 같던데 이거 사실인가요 어디서 본거 같...,0,1,[{'comment_content': '올해는 일단 유예됐는데 취소가 아니라 유예된...,cafe,2025-06-30,4,"[(추가, NNG), (의대, NNG), (증원, NNG), (이야기, NNG), ...","[추가, 의대, 증원, 이야기]","[(최근, NNG), (에, JKB), (뉴스, NNG), (보, VV), (니까,...","[최근, 뉴스, 의대, 추가, 증원, 사실, 검색, 추천, 강, 생물, 노용관, 이...","[올해, 유예, 취소, 유예, 회의, 내년, 증원, 결정]","[(올해, NNG), (는, JX), (일단, MAG), (유예, NNG), (되,..."
2,sky 질문,언미생사 all 백분위 96인 1이고 영어는 고정 1인데 서연고 중에 어디가 제일 ...,0,3,[{'comment_content': '뭐가 기준인지는 모르겠지만 수능은 생각보다 ...,cafe,2025-06-29,4,"[(sky, SL), (질문, NNG)]",[질문],"[(언미생사, NNP), (all, SL), (백분위, NNG), (96, SN),...","[언미생사, 백분위, 인, 영어, 고정, 연고, 유리, 올해, 재수, 의대, 증원,...","[기준, 수능, 생각, 스카이, 유리, 생각, 이유, 성적, 유리, 수미, 잡이, ...","[(뭐, NP), (가, JKS), (기준, NNG), (이, VCP), (ᆫ지, ..."
3,수시 6장 머리터지기 시작했어요,글쓰기 전 선검색 바랍니다 미취학글 과외구인글 아이디 추천글 댓글 달린 글 삭제시 ...,1,11,[{'comment_content': '전체내신나오고 아이의 생기부가 어느정도 파악...,cafe,2025-06-30,4,"[(수시, NNG), (6, SN), (장, NNG), (머리, NNG), (터지,...","[수시, 장, 머리, 시작]","[(글, NNG), (쓰, VV), (기, ETN), (전, NNG), (선, NN...","[글, 전, 선, 검색, 취학, 글, 과외, 구인, 글, 아이디, 추천, 글, 댓글...","[전체, 내신, 생기, 정도, 파악, 객관, 현재, 위치, 성향, 종합, 교과, 논...","[(전체, NNG), (내신, NNG), (나오, VV), (고, EC), (아이,..."
4,고3 수시 대학 라인 문제,고1 고3 필수 학종 합격 가이드 1 학생 학부모 여부 본인및 자녀의 학년 예 고3...,1,2,"[{'comment_content': '같은 고민 입니다 어렵네요', 'commen...",cafe,2025-06-30,4,"[(고, NNG), (3, SN), (수시, NNG), (대학, NNG), (라인,...","[고, 수시, 대학, 라인, 문제]","[(고, NNG), (1, SN), (고, NNG), (3, SN), (필수, NN...","[고, 고, 필수, 학종, 합격, 가이드, 학생, 학부모, 본인, 자녀, 학년, 고...","[고민, 안녕, 회원님유니브클래스, 카페, 회원, 축하, 처음, 유니브클래스, 카페...","[(같, VA), (은, ETM), (고민, NNG), (이, VCP), (ᆸ니다,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3707,서울대 수시 합격생 11 가 미등록,1 정치 및 종교 저작권 위반 타학원 및 관계자에 대한 지나친 표현의 글은 작성금지...,0,12,"[{'comment_content': '다들 의대가려고 그런가바요', 'commen...",cafe,2024-01-02,1,"[(서울대, NNP), (수시, NNG), (합격, NNG), (생, XSN), (...","[서울대, 수시, 합격, 등록]","[(1, SN), (정치, NNG), (및, MAG), (종교, NNG), (저작,...","[정치, 종교, 저작, 위반, 학원, 관계자, 표현, 글, 작성, 금지, 사이트, ...","[의대, 의대, 영향, 의대, 생각, 자연, 학생, 의대, 중복, 지원, 경우, 생...","[(다, NNG), (들, XSN), (의대, NNG), (가, VV), (려고, ..."
3708,의대 증원 관련 기사입니다,단독 이과 수험생 62 교차지원 고려 의대증원 노린 반수 늘 듯 동아일보 단독 이과...,0,4,"[{'comment_content': '점점 의대중심의 세상이 되어가네요', 'co...",cafe,2024-01-01,1,"[(의대, NNG), (증원, NNG), (관련, NNG), (기사, NNG), (...","[의대, 증원, 관련, 기사]","[(단독, NNG), (이과, NNG), (수험, NNG), (생, XSN), (6...","[단독, 이과, 수험, 교차, 지원, 고려, 의대, 증원, 반수, 동아일보, 단독,...","[의대, 중심, 세상, 나중, 의대, 취급, 다양, 직업, 존재, 의대, 의대, 열...","[(점점, MAG), (의대, NNG), (중심, NNG), (의, JKG), (세..."
3709,부끄러운 얘기지만 치과는 여러 곳 가보세요,부끄러운 얘기지만 치과는 여러 곳 가보세요 치과계 폭리 다룬 책 펴낸 치과의사 김광...,6,5,[{'comment_content': '20 30년 정도 오래된 치과에 가는 것을 ...,cafe,2024-01-01,1,"[(부끄럽, VA-I), (은, ETM), (얘기, NNG), (이, VCP), (...","[얘기, 치과, 곳]","[(부끄럽, VA-I), (은, ETM), (얘기, NNG), (이, VCP), (...","[얘기, 치과, 곳, 치과, 폭리, 책, 치과, 의사, 김광수, 치과, 폭리, 지적...","[정도, 치과, 추천, 조언, 대형, 치과, 상업, 자유, 갑진, 새해, 시작, 새...","[(20, SN), (30, SN), (년, NNB), (정도, NNG), (오래,..."
3710,2024년신년사 서울아산병원장 청라 개원 관련 여러번 언급,뉴스 행사2024년 신년사 서울아산병원장 박승일2024 01 01 2024년 갑진년...,54,18,[{'comment_content': '중입자치료기도입은 서울에 한다는걸까요 청라에...,cafe,2024-01-01,1,"[(2024, SN), (년, NNB), (신년사, NNG), (서울아산병원, NN...","[신년사, 서울아산병원, 장, 청라, 개원, 관련, 언급]","[(뉴스, NNG), (행사, NNG), (2024, SN), (년, NNB), (...","[뉴스, 행사, 신년사, 서울아산병원, 장, 박승일, 갑진, 새해, 서울아산병원, ...","[중입자, 치료기, 도입, 서울, 청라, 도입, 변화, 혁신, 미래, 청라, 도입,...","[(중입자, NNP), (치료기, NNG), (도입, NNG), (은, JX), (..."
3711,12월31일 아이가 어제 응급실 뺑뺑했어요,아이가 머리아프다는데 육안상 머리부분에 평소와 다른부분이 보이는데 119에서도 병원...,2,146,"[{'comment_content': '고생 많으셨습니다', 'comment_lik...",cafe,2024-01-01,1,"[(12, SN), (월, NNB), (31, SN), (일, NNB), (아이, ...",[응급실],"[(아이, NNG), (가, JKS), (머리, NNG), (아프, VA), (다는...","[머리, 육안, 머리, 부분, 평소, 부분, 병원, 집, 근처, 곳, 곳, 병원, ...","[고생, 병원, 순간, 대학, 병원, 병원, 최소, 운영, 의사, 소송, 위험, 기...","[(고생, NNG), (많, VA), (으시, EP), (었, EP), (습니다, ..."

In [65]:
data_drop_list = data.drop(columns=['title_token_list_pos', 'document_token_list_pos', 'comment_token_list_pos'])
f = open(DATA_CAFE_ONLY / "의대증원_cafedata_total_estate_press_drop_list_pos.pkl", 'wb')
pickle.dump(data_drop_list, f)
f.close()

In [67]:
f = open(DATA_CAFE_ONLY / "의대증원_cafedata_total_estate_press_drop_list_pos.pkl", 'rb')
d = pickle.load(f)
f.close()
d

,title,doc,like,comment_cnt,comment_list,ch,date,section,title_token_noun,document_token_noun,comment_token_noun
0,2026학년도 의과대학 수시모집 교과 일반전형 3,인제대는 작년 내신성적을 반영할 때 국영수 과학 상위 2과목만 반영하는 산식으로 다...,16,6,[{'comment_content': '잘 읽어보았습니다 한눈에 전체 내용이 잘 들...,cafe,2025-06-29,4,"[학년도, 의과, 대학, 수시, 모집, 교과, 일반, 전형]","[인제대, 작년, 내신, 성적, 반영, 국영수, 과학, 상위, 과목, 반영, 학교,...","[한눈, 전체, 내용, 부연, 설명, 감사, 객관, 인칭, 시점, 보믄, 파라미터,..."
1,추가 의대증원 이야기 나오던데,최근에 뉴스 보니까 의대 또 추가증원한다는것 같던데 이거 사실인가요 어디서 본거 같...,0,1,[{'comment_content': '올해는 일단 유예됐는데 취소가 아니라 유예된...,cafe,2025-06-30,4,"[추가, 의대, 증원, 이야기]","[최근, 뉴스, 의대, 추가, 증원, 사실, 검색, 추천, 강, 생물, 노용관, 이...","[올해, 유예, 취소, 유예, 회의, 내년, 증원, 결정]"
2,sky 질문,언미생사 all 백분위 96인 1이고 영어는 고정 1인데 서연고 중에 어디가 제일 ...,0,3,[{'comment_content': '뭐가 기준인지는 모르겠지만 수능은 생각보다 ...,cafe,2025-06-29,4,[질문],"[언미생사, 백분위, 인, 영어, 고정, 연고, 유리, 올해, 재수, 의대, 증원,...","[기준, 수능, 생각, 스카이, 유리, 생각, 이유, 성적, 유리, 수미, 잡이, ..."
3,수시 6장 머리터지기 시작했어요,글쓰기 전 선검색 바랍니다 미취학글 과외구인글 아이디 추천글 댓글 달린 글 삭제시 ...,1,11,[{'comment_content': '전체내신나오고 아이의 생기부가 어느정도 파악...,cafe,2025-06-30,4,"[수시, 장, 머리, 시작]","[글, 전, 선, 검색, 취학, 글, 과외, 구인, 글, 아이디, 추천, 글, 댓글...","[전체, 내신, 생기, 정도, 파악, 객관, 현재, 위치, 성향, 종합, 교과, 논..."
4,고3 수시 대학 라인 문제,고1 고3 필수 학종 합격 가이드 1 학생 학부모 여부 본인및 자녀의 학년 예 고3...,1,2,"[{'comment_content': '같은 고민 입니다 어렵네요', 'commen...",cafe,2025-06-30,4,"[고, 수시, 대학, 라인, 문제]","[고, 고, 필수, 학종, 합격, 가이드, 학생, 학부모, 본인, 자녀, 학년, 고...","[고민, 안녕, 회원님유니브클래스, 카페, 회원, 축하, 처음, 유니브클래스, 카페..."
...,...,...,...,...,...,...,...,...,...,...,...
3707,서울대 수시 합격생 11 가 미등록,1 정치 및 종교 저작권 위반 타학원 및 관계자에 대한 지나친 표현의 글은 작성금지...,0,12,"[{'comment_content': '다들 의대가려고 그런가바요', 'commen...",cafe,2024-01-02,1,"[서울대, 수시, 합격, 등록]","[정치, 종교, 저작, 위반, 학원, 관계자, 표현, 글, 작성, 금지, 사이트, ...","[의대, 의대, 영향, 의대, 생각, 자연, 학생, 의대, 중복, 지원, 경우, 생..."
3708,의대 증원 관련 기사입니다,단독 이과 수험생 62 교차지원 고려 의대증원 노린 반수 늘 듯 동아일보 단독 이과...,0,4,"[{'comment_content': '점점 의대중심의 세상이 되어가네요', 'co...",cafe,2024-01-01,1,"[의대, 증원, 관련, 기사]","[단독, 이과, 수험, 교차, 지원, 고려, 의대, 증원, 반수, 동아일보, 단독,...","[의대, 중심, 세상, 나중, 의대, 취급, 다양, 직업, 존재, 의대, 의대, 열..."
3709,부끄러운 얘기지만 치과는 여러 곳 가보세요,부끄러운 얘기지만 치과는 여러 곳 가보세요 치과계 폭리 다룬 책 펴낸 치과의사 김광...,6,5,[{'comment_content': '20 30년 정도 오래된 치과에 가는 것을 ...,cafe,2024-01-01,1,"[얘기, 치과, 곳]","[얘기, 치과, 곳, 치과, 폭리, 책, 치과, 의사, 김광수, 치과, 폭리, 지적...","[정도, 치과, 추천, 조언, 대형, 치과, 상업, 자유, 갑진, 새해, 시작, 새..."
3710,2024년신년사 서울아산병원장 청라 개원 관련 여러번 언급,뉴스 행사2024년 신년사 서울아산병원장 박승일2024 01 01 2024년 갑진년...,54,18,[{'comment_content': '중입자치료기도입은 서울에 한다는걸까요 청라에...,cafe,2024-01-01,1,"[신년사, 서울아산병원, 장, 청라, 개원, 관련, 언급]","[뉴스, 행사, 신년사, 서울아산병원, 장, 박승일, 갑진, 새해, 서울아산병원, ...","[중입자, 치료기, 도입, 서울, 청라, 도입, 변화, 혁신, 미래, 청라, 도입,..."
3711,12월31일 아이가 어제 응급실 뺑뺑했어요,아이가 머리아프다는데 육안상 머리부분에 평소와 다른부분이 보이는데 119에서도 병원...,2,146,"[{'comment_content': '고생 많으셨습니다', 'comment_lik...",cafe,2024-01-01,1,[응급실],"[머리, 육안, 머리, 부분, 평소, 부분, 병원, 집, 근처, 곳, 곳, 병원, ...","[고생, 병원, 순간, 대학, 병원, 병원, 최소, 운영, 의사, 소송, 위험, 기..."